'''
Created on July 14, 2015

@author: martin.melchior (at) fhnw.ch
'''

DRM_CONFIGURE = "DRM_CONFIGURE"
DRM_SUBMIT = "DRM_SUBMIT"
DRM_CHECKSTATUS = "DRM_CHECKSTATUS"
DRM_CLEANUP = "DRM_CLEANUP"
DRM_CANCEL = "DRM_CANCEL"

DRM_PROTOCOL = "DRM_PROTOCOL"
DRM_HOSTNAME = "DRM_HOSTNAME"

WS_PROTOCOL = "WS_PROTOCOL"
WS_HOSTNAME = "WS_HOSTNAME"
WS_ROOT = "WS_ROOT"

LOCALCACHE = "LOCALCACHE"

WFM_PROXYFCTS_ROOT = "WFM_PROXYFCTS_ROOT"
WFM_PKGDEFS_ROOT = "WFM_PKGDEFS_ROOT"
WFM_SCRIPTS_ROOT = "WFM_SCRIPTS_ROOT"

STATIC_FILES = "STATIC_FILES"
CODE_DIR = "CODE_DIR"
IMG_DIR = "IMG_DIR"
TEMPLATE_DIR = "TEMPLATE_DIR"

STATIC_CONFIG = None
